Repository primer/brand, pull requests merged in 2022-12, with the labels that each got.

#135 Stack Component Updates
  .changeset/itchy-cycles-relax.md
  apps/docs/content/components/Stack.mdx
  packages/react/src/Stack/Stack.stories.tsx
  packages/react/src/Stack/Stack.tsx
Labels: update snapshots

#133 AnchorNav component
  .changeset/itchy-carrots-yawn.md
  apps/docs/content/components/AnchorNav.mdx
  apps/docs/src/@primer/gatsby-theme-doctocat/nav.yml
  package-lock.json
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/src/tokens/functional/components/anchor-nav/colors.js
  packages/e2e/scripts/playwright/playwright.generate-tests.ts
  packages/react/.eslintrc.js
  packages/react/src/AnchorNav/AnchorNav.features.stories.tsx
  packages/react/src/AnchorNav/AnchorNav.module.css
  packages/react/src/AnchorNav/AnchorNav.module.css.d.ts
  packages/react/src/AnchorNav/AnchorNav.stories.tsx
  packages/react/src/AnchorNav/AnchorNav.test.tsx
  packages/react/src/AnchorNav/AnchorNav.tsx
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-AnchorNav-Custom-Background-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-AnchorNav-Default-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-AnchorNav-Fewer-anchor-links-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-AnchorNav-Playground-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-Mobile-viewport-t-59933--AnchorNav-Narrow-view-menu-open-mobile-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-Mobile-viewport-t-b1790-AnchorNav-Narrow-view-menu-closed-mobile-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-Tablet-viewport-t-60453-nchorNav-Regular-view-menu-closed-tablet-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-Tablet-viewport-t-c7556--AnchorNav-Regular-view-menu-open-tablet-1-linux.png
  packages/react/src/AnchorNav/index.ts
  packages/react/src/AnchorNav/useExpandedMenu.ts
  packages/react/src/LayoutExamples/LayoutExamples.stories.tsx
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-LayoutExamples-Kitchen-Sink-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-LayoutExamples-Resources-Hub-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-Mobile-viewp-1ba00-bile-LayoutExamples-Resources-Hub-mobile-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-Mobile-viewp-54fa0-obile-LayoutExamples-Kitchen-Sink-mobile-1-linux.png
  packages/react/src/LayoutExamples/Resources.tsx
  packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx
  packages/react/src/component-helpers.tsx
  packages/react/src/hooks/useWindowSize.ts
  packages/react/src/index.ts
  packages/react/src/test-utils/mocks/match-media-mock.ts
Labels: brand

#144 ComparisonTable minor fixes
  .changeset/popular-bugs-work.md
  apps/docs/content/components/ComparisonTable.mdx
  apps/docs/gatsby-config.js
  packages/react/src/ComparisonTable/ComparisonTable.module.css
  packages/react/src/ComparisonTable/ComparisonTable.visual.spec.ts-snapshots/Visual-Comparison-ComparisonTable-Mobile-view-44488-mobile-ComparisonTable-Playground-mobile-1-linux.png
Labels: documentation, update snapshots
