Repository primer/brand, pull requests merged in 2023-08, with the labels that each got.

#368 Update Link and InlineLink styles
  packages/design-tokens/src/tokens/functional/components/inline-link/colors.json
  packages/design-tokens/src/tokens/functional/components/link/colors.json
  packages/react/src/ActionMenu/ActionMenu.visual.spec.ts-snapshots/Visual-Comparison-ActionMenu-ActionMenu-Single-Selection-1-linux.png
  packages/react/src/Avatar/Avatar.visual.spec.ts-snapshots/Visual-Comparison-Avatar-Avatar-Default-1-linux.png
  packages/react/src/Box/Box.visual.spec.ts-snapshots/Visual-Comparison-Box-Box-Padding-1-linux.png
  packages/react/src/Button/Button.visual.spec.ts-snapshots/Visual-Comparison-Button-Button-Primary-1-linux.png
  packages/react/src/Link/Link.module.css
  packages/react/src/animation/animation.visual.spec.ts-snapshots/Visual-Comparison-animation-animation-Animation-On-Press-1-linux.png
Labels: update snapshots

#357 Bump doctocat from 4.4.2 to 4.6.1 in /apps/docs
  apps/docs/gatsby-config.js
  apps/docs/package-lock.json
  apps/docs/package.json
  apps/docs/src/@primer/gatsby-theme-doctocat/primer-nav.yml
  apps/docs/src/layouts/component-layout.tsx
  package-lock.json
Labels: documentation, skip changeset

#370 Update Pillar styles
  .changeset/ten-ways-clean.md
  packages/react/src/ActionMenu/ActionMenu.visual.spec.ts-snapshots/Visual-Comparison-ActionMenu-ActionMenu-Single-Selection-1-linux.png
  packages/react/src/Box/Box.visual.spec.ts-snapshots/Visual-Comparison-Box-Box-Padding-1-linux.png
  packages/react/src/Button/Button.visual.spec.ts-snapshots/Visual-Comparison-Button-Button-Primary-1-linux.png
  packages/react/src/Pillar/Pillar.features.stories.tsx
  packages/react/src/Pillar/Pillar.module.css
  packages/react/src/Pillar/Pillar.module.css.d.ts
  packages/react/src/Pillar/Pillar.tsx
  packages/react/src/Pillar/Pillar.visual.spec.ts
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Default-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Icon-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Icon-Colors-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Icon-native-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Link-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Playground-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Stacked-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Stacked-Centered-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Stacked-With-Link-1-linux.png
  packages/react/src/animation/animation.visual.spec.ts-snapshots/Visual-Comparison-animation-animation-Animation-On-Press-1-linux.png
Labels: update snapshots

#362 Added new logo suite component
  .changeset/odd-goats-raise.md
  .changeset/tall-penguins-walk.md
  apps/docs/content/components/Box/react.mdx
  apps/docs/content/components/LogoSuite/index.mdx
  apps/docs/content/components/LogoSuite/react.mdx
  apps/docs/scripts/components-with-animation.js
  apps/docs/src/@primer/gatsby-theme-doctocat/nav.yml
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/src/tokens/functional/components/logosuite/base.json
  packages/design-tokens/src/tokens/functional/components/logosuite/colors.json
  packages/e2e/scripts/playwright/playwright.generate-tests.ts
  packages/react/src/LayoutExamples/Resources.tsx
  packages/react/src/LogoSuite/LogoSuite.features.stories.tsx
  packages/react/src/LogoSuite/LogoSuite.module.css
  packages/react/src/LogoSuite/LogoSuite.module.css.d.ts
  packages/react/src/LogoSuite/LogoSuite.stories.tsx
  packages/react/src/LogoSuite/LogoSuite.test.tsx
  packages/react/src/LogoSuite/LogoSuite.tsx
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Align-Justified-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Align-Start-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Default-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Heading-Hidden-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Only-Description-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Only-Heading-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Playground-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Stacked-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-With-Emphasis-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-With-Links-1-linux.png
  packages/react/src/LogoSuite/index.ts
  packages/react/src/animation/Animation.features.stories.tsx
  packages/react/src/index.ts
Labels: brand

#346 [Radio] Design Guidelines
  apps/docs/content/components/Radio/index.mdx
  apps/docs/content/components/Radio/react.mdx
Labels: documentation, skip changeset

#375 Bump Doctocat 4.6.3
  apps/docs/package-lock.json
  apps/docs/package.json
Labels: skip changeset, update snapshots

#378 [Pillar] Update documentation
  apps/docs/content/components/Pillar/index.mdx
Labels: skip changeset

#352 [Feature] Button Full Width (block prop)
  .changeset/mean-turkeys-drive.md
  apps/docs/content/components/Button/index.mdx
  apps/docs/content/components/Button/react.mdx
  package-lock.json
  packages/react/src/Button/Button.features.stories.tsx
  packages/react/src/Button/Button.module.css
  packages/react/src/Button/Button.module.css.d.ts
  packages/react/src/Button/Button.stories.tsx
  packages/react/src/Button/Button.test.tsx
  packages/react/src/Button/Button.tsx
  packages/react/src/Button/Button.visual.spec.ts
  packages/react/src/Button/Button.visual.spec.ts-snapshots/Visual-Comparison-Button-Button-Block-1-linux.png
Labels: update snapshots

#380 Add Timeline component
  .changeset/heavy-birds-visit.md
  apps/docs/content/components/Timeline.mdx
  apps/docs/src/@primer/gatsby-theme-doctocat/nav.yml
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/src/tokens/functional/components/timeline/base.json
  packages/design-tokens/src/tokens/functional/components/timeline/colors.json
  packages/react/src/Avatar/Avatar.visual.spec.ts-snapshots/Visual-Comparison-Avatar-Avatar-Default-1-linux.png
  packages/react/src/Timeline/Timeline.features.stories.tsx
  packages/react/src/Timeline/Timeline.module.css
  packages/react/src/Timeline/Timeline.module.css.d.ts
  packages/react/src/Timeline/Timeline.stories.tsx
  packages/react/src/Timeline/Timeline.test.tsx
  packages/react/src/Timeline/Timeline.tsx
  packages/react/src/Timeline/Timeline.visual.spec.ts
  packages/react/src/Timeline/Timeline.visual.spec.ts-snapshots/Visual-Comparison-Timeline-Timeline-Default-1-linux.png
  packages/react/src/Timeline/index.ts
  packages/react/src/index.ts
Labels: brand, update snapshots

#345 [Checkbox] Design Guidelines
  apps/docs/content/components/Checkbox/index.mdx
  apps/docs/content/components/Checkbox/react.mdx
  package-lock.json
Labels: documentation, skip changeset

#381 Improve trailingComponent feature of River.Content
  .changeset/young-crabs-taste.md
  packages/react/src/River/River.fixtures.stories.tsx
  packages/react/src/River/River.module.css
  packages/react/src/River/River.module.css.d.ts
  packages/react/src/River/River.tsx
  packages/react/src/River/River.visual.spec.ts
  packages/react/src/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Custom-trailing-content-1-linux.png
  packages/react/src/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Custom-trailing-content-w-divider-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Conditional-Rendering-1-linux.png
  packages/react/src/Timeline/Timeline.visual.spec.ts
  packages/react/src/Timeline/Timeline.visual.spec.ts-snapshots/Visual-Comparison-Timeline-Timeline-Default-1-linux.png
  packages/react/src/Timeline/Timeline.visual.spec.ts-snapshots/Visual-Comparison-Timeline-Timeline-With-Emphasis-1-linux.png
Labels: brand

#398 Remove small Label variant
  .changeset/gold-shirts-rescue.md
  apps/docs/content/components/Label/index.mdx
  apps/docs/content/components/Label/react.mdx
  packages/react/src/Card/Card.tsx
  packages/react/src/Hero/Hero.test.tsx
  packages/react/src/Hero/Hero.tsx
  packages/react/src/Label/Label.features.stories.tsx
  packages/react/src/Label/Label.module.css
  packages/react/src/Label/Label.module.css.d.ts
  packages/react/src/Label/Label.tsx
  packages/react/src/Label/Label.visual.spec.ts
  packages/react/src/SectionIntro/SectionIntro.test.tsx
  packages/react/src/SectionIntro/SectionIntro.tsx
  packages/react/src/river/River/River.visual.spec.ts
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts-snapshots/Visual-Comparison-RiverBreakout-RiverBreakout-Default-1-linux.png
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts-snapshots/Visual-Comparison-RiverBreakout-RiverBreakout-Highlighted-Portion-1-linux.png
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts-snapshots/Visual-Comparison-RiverBreakout-RiverBreakout-Without-Trailing-Component-1-linux.png
Labels: update snapshots

#372 2023 refactor for the large Testimonial
  .changeset/modern-kings-live.md
  apps/docs/content/components/Testimonial/react.mdx
  packages/design-tokens/src/tokens/functional/components/testimonial/base.json
  packages/design-tokens/src/tokens/functional/components/testimonial/colors.json
  packages/react/src/Testimonial/Testimonial.module.css
  packages/react/src/Testimonial/Testimonial.module.css.d.ts
  packages/react/src/Testimonial/Testimonial.stories.tsx
  packages/react/src/Testimonial/Testimonial.tsx
  packages/react/src/Testimonial/Testimonial.visual.spec.ts
Labels: update snapshots

#402 Enable private storybook instance
  .github/workflows/deploy_docs.yml
  apps/docs/content/github-staff/storybook.mdx
  apps/docs/scripts/components-with-animation.js
  apps/docs/src/@primer/gatsby-theme-doctocat/nav.yml
  apps/storybook/.storybook/manager.js
  apps/storybook/src/images/mona-recipes.png
  apps/storybook/src/theme.js
  package-lock.json
  packages/react/src/Avatar/Avatar.visual.spec.ts-snapshots/Visual-Comparison-Avatar-Avatar-Default-1-linux.png
Labels: skip changeset

#411 Update theming.mdx
  apps/docs/content/getting-started/theming.mdx
Labels: skip changeset
