Repository primer/brand, pull requests merged in 2023-10, with the labels that each got.

#439 [Site refactor] Documentation update
  apps/docs/content/components/CTABanner/index.mdx
  apps/docs/content/components/CTAForm/index.mdx
  apps/docs/content/components/FAQ/index.mdx
  apps/docs/content/components/Grid/index.mdx
  apps/docs/content/components/Heading/index.mdx
  apps/docs/content/components/Label/index.mdx
  apps/docs/content/components/River/index.mdx
Labels: skip changeset

#438 [Site refactor] Update Testimonial documentation
  apps/docs/content/components/Testimonial/index.mdx
Labels: skip changeset

#435 [Prose] Add `code` and `blockquote`
  .changeset/friendly-suns-tease.md
  apps/docs/content/components/Prose.mdx
  apps/docs/scripts/components-with-animation.js
  packages/design-tokens/src/tokens/functional/components/prose/base.json
  packages/react/src/Prose/Prose.features.stories.tsx
  packages/react/src/Prose/Prose.module.css
  packages/react/src/Prose/Prose.stories.tsx
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Mobile-viewport-test--ac684-ile-Prose-Narrow-view-full-width-mobile-1-linux.png
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Prose-Default-1-linux.png
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Prose-Full-Width-1-linux.png
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Prose-Playground-1-linux.png
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Tablet-viewport-test--1534f-et-Prose-Regular-view-full-width-tablet-1-linux.png
Labels: update snapshots

#469 Update aria-label on GitHub link
  .changeset/perfect-mirrors-report.md
  packages/react/src/MinimalFooter/MinimalFooter.tsx
Labels: brand, update snapshots

#457 Prose list style image fix
  .changeset/purple-books-sneeze.md
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/src/tokens/functional/components/prose/colors.js
  packages/react/src/Prose/Prose.features.stories.tsx
  packages/react/src/Prose/Prose.module.css
  packages/react/src/Prose/Prose.tsx
  packages/react/src/Prose/Prose.visual.spec.ts
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Prose-Unordered-List-1-linux.png
Labels: brand, update snapshots

#476 Update side-by-side recipe with sign in banner
  packages/e2e/scripts/playwright/playwright.generate-tests.ts
  packages/react/src/ActionMenu/ActionMenu.visual.spec.ts-snapshots/Visual-Comparison-ActionMenu-ActionMenu-Disabled-Item-1-linux.png
  packages/react/src/ActionMenu/ActionMenu.visual.spec.ts-snapshots/Visual-Comparison-ActionMenu-ActionMenu-Longer-lists-open-1-linux.png
  packages/react/src/ActionMenu/ActionMenu.visual.spec.ts-snapshots/Visual-Comparison-ActionMenu-ActionMenu-Menu-alignment-end-1-linux.png
  packages/react/src/ActionMenu/ActionMenu.visual.spec.ts-snapshots/Visual-Comparison-ActionMenu-ActionMenu-Open-By-Default-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-Mobile-viewport-t-59933--AnchorNav-Narrow-view-menu-open-mobile-1-linux.png
  packages/react/src/AnchorNav/AnchorNav.visual.spec.ts-snapshots/Visual-Comparison-AnchorNav-Tablet-viewport-t-c7556--AnchorNav-Regular-view-menu-open-tablet-1-linux.png
  packages/react/src/Avatar/Avatar.visual.spec.ts-snapshots/Visual-Comparison-Avatar-Avatar-Shapes-1-linux.png
  packages/react/src/Avatar/Avatar.visual.spec.ts-snapshots/Visual-Comparison-Avatar-Avatar-Sizes-1-linux.png
  packages/react/src/Box/Box.visual.spec.ts-snapshots/Visual-Comparison-Box-Box-Default-1-linux.png
  packages/react/src/Card/Card.visual.spec.ts-snapshots/Visual-Comparison-Card-Card-CTA-Text-1-linux.png
  packages/react/src/Card/Card.visual.spec.ts-snapshots/Visual-Comparison-Card-Card-Shadow-1-linux.png
  packages/react/src/ComparisonTable/ComparisonTable.visual.spec.ts-snapshots/Visual-Comparison-ComparisonTable-ComparisonTable-Playground-1-linux.png
  packages/react/src/FAQ/FAQ.visual.spec.ts-snapshots/Visual-Comparison-FAQ-FAQ-Reversed-Toggles-1-linux.png
  packages/react/src/Heading/Heading.visual.spec.ts-snapshots/Visual-Comparison-Heading-Heading-Scale-1-linux.png
  packages/react/src/Hero/Hero.visual.spec.ts-snapshots/Visual-Comparison-Hero-Hero-Narrow-View-1-linux.png
  packages/react/src/Hero/Hero.visual.spec.ts-snapshots/Visual-Comparison-Hero-Hero-Narrow-View-Centered-1-linux.png
  packages/react/src/Image/Image.visual.spec.ts-snapshots/Visual-Comparison-Image-Image-Features-1-linux.png
  packages/react/src/Label/Label.visual.spec.ts-snapshots/Visual-Comparison-Label-Label-Small-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-LayoutExamples-Kitchen-Sink-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-LayoutExamples-Resources-Hub-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-Mobile-viewp-1ba00-bile-LayoutExamples-Resources-Hub-mobile-1-linux.png
  packages/react/src/LayoutExamples/LayoutExamples.visual.spec.ts-snapshots/Visual-Comparison-LayoutExamples-Mobile-viewp-54fa0-obile-LayoutExamples-Kitchen-Sink-mobile-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Only-Description-1-linux.png
  packages/react/src/LogoSuite/LogoSuite.visual.spec.ts-snapshots/Visual-Comparison-LogoSuite-LogoSuite-Stacked-1-linux.png
  packages/react/src/MinimalFooter/MinimalFooter.visual.spec.ts-snapshots/Visual-Comparison-MinimalFooter-MinimalFooter-Button-Links-1-linux.png
  packages/react/src/MinimalFooter/MinimalFooter.visual.spec.ts-snapshots/Visual-Comparison-MinimalFooter-MinimalFooter-Dark-Theme-1-linux.png
  packages/react/src/MinimalFooter/MinimalFooter.visual.spec.ts-snapshots/Visual-Comparison-MinimalFooter-MinimalFooter-Filtered-Social-Links-1-linux.png
  packages/react/src/MinimalFooter/MinimalFooter.visual.spec.ts-snapshots/Visual-Comparison-MinimalFooter-MinimalFooter-No-Social-Links-1-linux.png
  packages/react/src/MinimalFooter/MinimalFooter.visual.spec.ts-snapshots/Visual-Comparison-MinimalFooter-MinimalFooter-Playground-1-linux.png
  packages/react/src/Pillar/Pillar.visual.spec.ts-snapshots/Visual-Comparison-Pillar-Pillar-Icon-Colors-1-linux.png
  packages/react/src/Prose/Prose.visual.spec.ts-snapshots/Visual-Comparison-Prose-Prose-Unordered-List-1-linux.png
  packages/react/src/SectionIntro/SectionIntro.visual.spec.ts-snapshots/Visual-Comparison-SectionIntro-SectionIntro-With-Subtle-Action-1-linux.png
  packages/react/src/Stack/Stack.visual.spec.ts-snapshots/Visual-Comparison-Stack-Stack-Playground-1-linux.png
  packages/react/src/Stack/Stack.visual.spec.ts-snapshots/Visual-Comparison-Stack-Stack-Responsive-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Longer-Title-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-No-Search-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-No-Title-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-No-overflow-menu-1-link-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Overflow-Menu-Open-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Playground-1-linux.png
  packages/react/src/Testimonial/Testimonial.visual.spec.ts-snapshots/Visual-Comparison-Testimonial-Testimonial-Highlighted-Portion-1-linux.png
  packages/react/src/Text/Text.visual.spec.ts-snapshots/Visual-Comparison-Text-Text-Default-1-linux.png
  packages/react/src/Text/Text.visual.spec.ts-snapshots/Visual-Comparison-Text-Text-Playground-1-linux.png
  packages/react/src/VideoPlayer/VideoPlayer.visual.spec.ts-snapshots/Visual-Comparison-VideoPlayer-VideoPlayer-Default-1-linux.png
  packages/react/src/VideoPlayer/VideoPlayer.visual.spec.ts-snapshots/Visual-Comparison-VideoPlayer-VideoPlayer-Playground-1-linux.png
  packages/react/src/VideoPlayer/VideoPlayer.visual.spec.ts-snapshots/Visual-Comparison-VideoPlayer-VideoPlayer-With-Poster-1-linux.png
  packages/react/src/VideoPlayer/VideoPlayer.visual.spec.ts-snapshots/Visual-Comparison-VideoPlayer-VideoPlayer-Without-Branding-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelOne/FeaturePreviewLevelOne.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelOne-FeaturePreviewLevelOne-Default-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelOne/FeaturePreviewLevelOne.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelOne-FeaturePreviewLevelOne-Level-1-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelOne/FeaturePreviewLevelOne.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelOne-FeaturePreviewLevelOne-Side-by-side---Enteprise-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelOne/FeaturePreviewLevelOne.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelOne-FeaturePreviewLevelOne-Side-by-side-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelOne/FeaturePreviewLevelOneSideBySide.tsx
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelOne/components/FormExample.tsx
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-1-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-Playground-1-linux.png
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts-snapshots/Visual-Comparison-RiverBreakout-RiverBreakout-Default-1-linux.png
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts-snapshots/Visual-Comparison-RiverBreakout-RiverBreakout-Highlighted-Portion-1-linux.png
  packages/react/src/river/RiverBreakout/RiverBreakout.visual.spec.ts-snapshots/Visual-Comparison-RiverBreakout-RiverBreakout-Without-Trailing-Component-1-linux.png
Labels: skip changeset

#451 SubdomainNavBar overflow fix
  .changeset/friendly-deers-obey.md
  packages/e2e/scripts/playwright/playwright.generate-tests.ts
  packages/react/src/SubdomainNavBar/NavigationVisbilityObserver.tsx
  packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css
  packages/react/src/SubdomainNavBar/SubdomainNavBar.module.css.d.ts
  packages/react/src/SubdomainNavBar/SubdomainNavBar.stories.tsx
  packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-16bce-le-No-Links-SubdomainNavBar-Mobile-No-Links-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-8d921-for-Mobile-View-SubdomainNavBar-Mobile-View-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-98fdb-SubdomainNavBar-Mobile-Menu-Open-Many-Items-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-e88bc--Menu-Open-SubdomainNavBar-Mobile-Menu-Open-1-linux.png
Labels: brand, update snapshots

#480 SubdomainNavbarMenu Focus Trapping
  .changeset/light-kings-clap.md
  packages/react/src/SubdomainNavBar/SubdomainNavBar.tsx
Labels: brand

#485 Fix Next14 Integration Tests
  .github/workflows/integration_test_nextjs.yml
Labels: brand, skip changeset
