Repository primer/brand, pull requests merged in 2024-09, with the labels that each got.

#725 Add interface guidelines for RiverStoryScroll
  apps/docs/content/components/River/images/do-visuals-size.png
  apps/docs/content/components/River/images/dont-visuals-size.png
  apps/docs/content/components/River/index.mdx
Labels: skip changeset

#730 Remove unused formats and other cleanup
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/scripts/style-dictionary.js
Labels: skip changeset

#741 Cleanup by removing some unneeded transforms and moving a format into a file
  package-lock.json
  packages/design-tokens/package.json
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/scripts/style-dictionary.js
  packages/design-tokens/src/formats/color-mode-attributes.js
  packages/design-tokens/src/formats/responsive-media-query.js
  packages/design-tokens/src/formats/typescript-module-declarations-v2.js
Labels: skip changeset

#739 Update SubNav docs to clarify SubNav.Heading semantic behaviour
  .changeset/hip-forks-taste.md
  apps/docs/content/components/SubNav.mdx
  packages/react/src/Bento/Bento.visual.spec.ts-snapshots/Visual-Comparison-Bento-Bento-Default-1-linux.png
  packages/react/src/SubNav/SubNav.module.css
  packages/react/src/SubNav/SubNav.module.css.d.ts
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-1-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-2-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-3-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-4-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-Playground-1-linux.png
Labels: update snapshots

#735 Fix Testimonial stories with flexible container
  packages/react/src/Footnotes/Footnotes.visual.spec.ts-snapshots/Visual-Comparison-Footnotes-Footnotes-Rivers-With-Citations-1-linux.png
  packages/react/src/PricingOptions/PricingOptions.visual.spec.ts-snapshots/Visual-Comparison-PricingOptions-PricingOptions-Cards-Variant-1-linux.png
  packages/react/src/PricingOptions/PricingOptions.visual.spec.ts-snapshots/Visual-Comparison-PricingOptions-PricingOptions-Three-Options-1-linux.png
  packages/react/src/Testimonial/Testimonial.stories.tsx
  packages/react/src/Testimonial/Testimonial.visual.spec.ts-snapshots/Visual-Comparison-Testimonial-Testimonial-Colored-Quote-Mark-1-linux.png
  packages/react/src/Testimonial/Testimonial.visual.spec.ts-snapshots/Visual-Comparison-Testimonial-Testimonial-Large-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-1-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-2-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-4-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-Playground-1-linux.png
  packages/react/src/recipes/seo/Article/Article.visual.spec.ts-snapshots/Visual-Comparison-Article-Article-Ai-Theme-1-linux.png
Labels: skip changeset, update snapshots

#749 Enforce `RiverStoryScroll` children are Rivers using types
  packages/react/src/river/RiverStoryScroll/RiverStoryScroll.tsx
  packages/react/src/river/RiverStoryScroll/RiverStoryScrollResponder.tsx
  packages/react/src/river/RiverStoryScroll/RiverStoryScrollTracker.tsx
Labels: update snapshots

#753 Add Figma code connect forn River component
  .eslintrc.js
  packages/react/src/river/River.figma.tsx
Labels: skip changeset

#755 Remove namespace from js token files
  packages/design-tokens/scripts/build-tokens.js
  packages/design-tokens/src/tokens/functional/components/accordion/colors.js
  packages/design-tokens/src/tokens/functional/components/action-menu/colors.js
  packages/design-tokens/src/tokens/functional/components/anchor-nav/colors.js
  packages/design-tokens/src/tokens/functional/components/breadcrumbs/colors.js
  packages/design-tokens/src/tokens/functional/components/button/colors.js
  packages/design-tokens/src/tokens/functional/components/comparison-table/colors.js
  packages/design-tokens/src/tokens/functional/components/control/colors.js
  packages/design-tokens/src/tokens/functional/components/cta-banner/colors.js
  packages/design-tokens/src/tokens/functional/components/eyebrow-banner/colors.js
  packages/design-tokens/src/tokens/functional/components/ide/colors.js
  packages/design-tokens/src/tokens/functional/components/pagination/colors.js
  packages/design-tokens/src/tokens/functional/components/prose/colors.js
  packages/design-tokens/src/tokens/functional/components/river-story-scroll/colors.js
  packages/design-tokens/src/tokens/functional/components/sub-nav/colors.js
  packages/design-tokens/src/tokens/functional/components/subdomain-nav-bar/colors.js
  packages/design-tokens/src/tokens/functional/components/video-player/colors.js
Labels: skip changeset

#760 Use clsx to combine HeroLabel and HeroEyebrow classnames
  .changeset/ninety-taxis-lick.md
  packages/react/src/Hero/Hero.tsx
Labels: update snapshots

#766 Add paddings to large river content
  .changeset/spotty-years-add.md
  packages/react/src/EyebrowBanner/EyebrowBanner.visual.spec.ts-snapshots/Visual-Comparison-EyebrowBanner-EyebrowBanner-Variations-1-linux.png
  packages/react/src/Footnotes/Footnotes.visual.spec.ts-snapshots/Visual-Comparison-Footnotes-Footnotes-Rivers-With-Citations-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Full-Width-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Longer-Title-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-No-Search-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-No-overflow-menu-1-link-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Playground-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Search-Open-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-SubdomainNavBar-Search-Results-Visible-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-1-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-2-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-3-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-2-4-variant-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-Minimal-1-linux.png
  packages/react/src/recipes/FeaturePreviewLPs/FeaturePreviewLevelTwo/FeaturePreviewLevelTwo.visual.spec.ts-snapshots/Visual-Comparison-FeaturePreviewLevelTwo-FeaturePreviewLevelTwo-Playground-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/Industry/Industry.visual.spec.ts-snapshots/Visual-Comparison-Industry-Industry-Maximum-Dark-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/Industry/Industry.visual.spec.ts-snapshots/Visual-Comparison-Industry-Industry-Maximum-Light-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/Size/Size.visual.spec.ts-snapshots/Visual-Comparison-Size-Size-Maximum-Dark-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/Size/Size.visual.spec.ts-snapshots/Visual-Comparison-Size-Size-Maximum-Light-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/Size/Size.visual.spec.ts-snapshots/Visual-Comparison-Size-Size-Minimum-Dark-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/Size/Size.visual.spec.ts-snapshots/Visual-Comparison-Size-Size-Minimum-Light-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/UseCase/UseCase.visual.spec.ts-snapshots/Visual-Comparison-UseCase-UseCase-Maximum-Dark-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/UseCase/UseCase.visual.spec.ts-snapshots/Visual-Comparison-UseCase-UseCase-Maximum-Light-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/UseCase/UseCase.visual.spec.ts-snapshots/Visual-Comparison-UseCase-UseCase-Minimum-Dark-1-linux.png
  packages/react/src/recipes/SolutionTemplates/SolutionPage/UseCase/UseCase.visual.spec.ts-snapshots/Visual-Comparison-UseCase-UseCase-Minimum-Light-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-60-40-image-ratio-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Alternating-Layout-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Alternative-Heading-Level-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Alternative-Heading-Size-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Copilot-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Custom-trailing-content-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Custom-trailing-content-w-divider-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Default-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Larger-Placeholder-Image-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Left-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-No-Rounded-Visual-Corners-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-Right-1-linux.png
  packages/react/src/river/River/River.visual.spec.ts-snapshots/Visual-Comparison-River-River-With-Label-1-linux.png
  packages/react/src/river/RiverStoryScroll/RiverStoryScroll.visual.spec.ts-snapshots/Visual-Comparison-RiverStoryScroll-RiverStoryScroll-Default-1-linux.png
  packages/react/src/river/RiverStoryScroll/RiverStoryScroll.visual.spec.ts-snapshots/Visual-Comparison-RiverStoryScroll-RiverStoryScroll-Disabled-1-linux.png
  packages/react/src/river/RiverStoryScroll/RiverStoryScroll.visual.spec.ts-snapshots/Visual-Comparison-RiverStoryScroll-RiverStoryScroll-Enterprise-Example-1-linux.png
  packages/react/src/river/RiverStoryScroll/RiverStoryScroll.visual.spec.ts-snapshots/Visual-Comparison-RiverStoryScroll-RiverStoryScroll-With-Timeline-1-linux.png
  packages/react/src/river/river-shared.module.css
Labels: update snapshots

#767 Update River content and visual order
  .changeset/sweet-waves-matter.md
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-2fbdc-bdomainNavBar-Mobile-Search-Results-Visible-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-8d921-for-Mobile-View-SubdomainNavBar-Mobile-View-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-98fdb-SubdomainNavBar-Mobile-Menu-Open-Many-Items-1-linux.png
  packages/react/src/SubdomainNavBar/SubdomainNavBar.visual.spec.ts-snapshots/Visual-Comparison-SubdomainNavBar-Mobile-view-e88bc--Menu-Open-SubdomainNavBar-Mobile-Menu-Open-1-linux.png
  packages/react/src/river/River/River.test.tsx
  packages/react/src/river/River/River.tsx
  packages/react/src/river/river-shared.module.css
  packages/react/src/river/river-shared.module.css.d.ts
Labels: update snapshots
